trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    ./gradlew --version
  displayName: "Version Info"

- task: Gradle@2
  inputs:
    tasks: 'build'
    gradleWrapperFile: 'gradlew'
#    gradleOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: 'false'
    testResultsFiles: 'build/test-results/test/TEST-*.xml'
